/* eslint-disable */
// AUTO-GENERATED by scripts/sync-oss-data.mjs — do not edit by hand
// Source: https://raw.githubusercontent.com/AsifAd/opensource-contributions/main/docs/assets/data/contributions.json

export type GeneratedOpenSourceStack = {
  tech: string;
  name: string;
  status: "active" | "planned" | "exploring";
  statusLabel: string;
  focus: string;
  openPRs: number;
  hubLink: string;
  prNote: string;
};

export const openSourceStacks: GeneratedOpenSourceStack[] = [
  {
    "tech": "ansible",
    "name": "Ansible",
    "status": "active",
    "statusLabel": "Active",
    "focus": "Keycloak #11747 — email_verified idempotency + check mode",
    "openPRs": 1,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-ansible",
    "prNote": " · 1 open PR"
  },
  {
    "tech": "argocd",
    "name": "Argo CD",
    "status": "active",
    "statusLabel": "Active",
    "focus": "Await review — #27932 Refresh",
    "openPRs": 1,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-argocd",
    "prNote": " · 1 open PR"
  },
  {
    "tech": "jenkins",
    "name": "Jenkins",
    "status": "active",
    "statusLabel": "Active",
    "focus": "kubernetes-plugin #2809 — multi-container pod cleanup (solo)",
    "openPRs": 0,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-jenkins",
    "prNote": ""
  },
  {
    "tech": "nifi",
    "name": "Apache NiFi",
    "status": "planned",
    "statusLabel": "Planned",
    "focus": "Provenance repo corruption after OOM on NiFi 1.27.0",
    "openPRs": 0,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-nifi",
    "prNote": ""
  },
  {
    "tech": "vault",
    "name": "Vault / OpenBao",
    "status": "planned",
    "statusLabel": "Planned",
    "focus": "community.hashi_vault #476 docs or OpenBao good-first issue",
    "openPRs": 0,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-vault",
    "prNote": ""
  },
  {
    "tech": "kubernetes",
    "name": "Kubernetes",
    "status": "exploring",
    "statusLabel": "Exploring",
    "focus": "kubernetes/website docs PR or kubernetes.core #1042",
    "openPRs": 0,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-kubernetes",
    "prNote": ""
  },
  {
    "tech": "docker",
    "name": "Docker",
    "status": "exploring",
    "statusLabel": "Exploring",
    "focus": "community.docker #790 — check-mode permanent diff",
    "openPRs": 0,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-docker",
    "prNote": ""
  },
  {
    "tech": "terraform",
    "name": "Terraform",
    "status": "exploring",
    "statusLabel": "Exploring",
    "focus": "Provider aligned with production use (TBD)",
    "openPRs": 0,
    "hubLink": "https://asifad.github.io/opensource-contributions/#roadmap-terraform",
    "prNote": ""
  }
];
